Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -59,12 +59,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Install dependencies
+      - name: Check if base64 is available
+        run: which base64 || echo "base64 command is missing"
+      - name: Install base64 if missing
+        if: failure() # Install base64 only if the previous step fails
         run: sudo apt-get update && sudo apt-get install -y coreutils
       - name: Create kubeconfig
         run: |
           mkdir ${HOME}/.kube
-          echo ${{ secrets.KUBE_CONFIG }} | base 64 --decode > ${HOME}/.kube/config
+          echo "${{ secrets.KUBE_CONFIG }}" | base 64 --decode > ${HOME}/.kube/config
           cat ${HOME}.kube/config
       - name: Use context 
         run: kubectl config use-context octobay-api
